# Generated by Django 4.0.6 on 2023-02-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='subject',
            field=models.CharField(choices=[('CREATE_REQUESTING', '오더 신청'), ('CREATE_BULK_REQUESTING', '대량 오더 신청'), ('REMINDING_CREATED_REQUESTING', '미배차 오더 리마인딩'), ('START_EVALUATION', '평카(검수) 시작'), ('FINISH_EVALUATION', '평카(검수) 종료'), ('CLIENT_PURCHASE_DECISION', '의뢰인 매입결정 결과'), ('DEPARTURE_DELIVERY', '탁송 시작'), ('ARRIVAL_DELIVERY', '탁송 완료'), ('CLIENT_CONFIRM_ARRIVAL_DELIVERY', '의뢰인 인도 확인'), ('REQUESTING_CHATTING', '의뢰 채팅')], max_length=32, verbose_name='알림 주제'),
        ),
    ]
