# Generated by Django 4.0.6 on 2022-09-15 15:33

from django.db import migrations, models
import django.db.models.deletion
import pcar.helpers
import requestings.models.bulk_requesting
import requestings.models.delivery_result
import requestings.models.external_evaluation_template
import requestings.models.requesting_additional_cost
import requestings.models.requesting_chatting_message
import requestings.models.review


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BulkRequesting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='올린 시각')),
                ('file', models.FileField(upload_to=pcar.helpers.PreprocessUploadPath(requestings.models.bulk_requesting.file_path_getter, use_uuid_name=True), verbose_name='다량 발주 파일')),
                ('is_processed', models.BooleanField(default=False, verbose_name='처리여부')),
            ],
            options={
                'verbose_name': '다량 발주',
                'verbose_name_plural': '다량 발주 목록',
                'db_table': 'bulk_requestings',
            },
        ),
        migrations.CreateModel(
            name='CarAccidentSiteImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_before_delivery', models.BooleanField(verbose_name='탁송 전 사진')),
                ('image', models.ImageField(upload_to=pcar.helpers.PreprocessUploadPath(requestings.models.delivery_result.car_condition_image_path_getter, use_uuid_name=True), verbose_name='차량 상태 이미지')),
            ],
            options={
                'verbose_name': '사고 부위 사진',
                'verbose_name_plural': '사고 부위 사진 목록',
                'db_table': 'car_accident_site_images',
            },
        ),
        migrations.CreateModel(
            name='CarBasicImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_before_delivery', models.BooleanField(verbose_name='탁송 전 사진')),
                ('image', models.ImageField(upload_to=pcar.helpers.PreprocessUploadPath(requestings.models.delivery_result.car_condition_image_path_getter, use_uuid_name=True), verbose_name='차량 상태 이미지')),
            ],
            options={
                'verbose_name': '기본 사진',
                'verbose_name_plural': '기본 사진 목록',
                'db_table': 'car_basic_images',
            },
        ),
        migrations.CreateModel(
            name='DeliveryAsset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=pcar.helpers.PreprocessUploadPath(requestings.models.delivery_result.delivery_asset_image_path_getter, use_uuid_name=True), verbose_name='이미지')),
            ],
            options={
                'verbose_name': '탁송 관련 에셋',
                'verbose_name_plural': '탁송 관련 에셋 목록',
                'db_table': 'delivery_assets',
            },
        ),
        migrations.CreateModel(
            name='DeliveryResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mileage_before_delivery', models.IntegerField(verbose_name='탁송 전 현재 주행거리')),
                ('mileage_after_delivery', models.IntegerField(blank=True, null=True, verbose_name='차량 입고시 주행거리')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='특이사항')),
            ],
            options={
                'verbose_name': '탁송 결과',
                'verbose_name_plural': '탁송 결과 목록',
                'db_table': 'delivery_results',
            },
        ),
        migrations.CreateModel(
            name='ExternalEvaluationTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='템플릿 이름')),
                ('file', models.FileField(upload_to=pcar.helpers.PreprocessUploadPath(requestings.models.external_evaluation_template.template_file_getter, use_uuid_name=True))),
            ],
            options={
                'verbose_name': '외부 평가지 양식',
                'verbose_name_plural': '외부 평가지 양식 목록',
                'db_table': 'external_evaluation_templates',
            },
        ),
        migrations.CreateModel(
            name='RequestingAdditionalCost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='추가 비용 내용')),
                ('cost', models.IntegerField(verbose_name='추가 비용')),
                ('working_type', models.CharField(blank=True, choices=[('EVALUATION/INSPECTION', '평카/검수'), ('DELIVERY', '탁송')], max_length=50, null=True, verbose_name='추가 비용 발생 작업 구분')),
                ('image', models.ImageField(blank=True, null=True, upload_to=pcar.helpers.PreprocessUploadPath(requestings.models.requesting_additional_cost.template_file_getter, use_uuid_name=True), verbose_name='추가비용 증빙 이미지')),
            ],
            options={
                'verbose_name': '추가 요금',
                'verbose_name_plural': '추가 요금 목록',
                'db_table': 'requesting_additional_costs',
            },
        ),
        migrations.CreateModel(
            name='RequestingChattingMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text', models.CharField(blank=True, max_length=300, null=True, verbose_name='채팅 메시지')),
                ('sending_to', models.CharField(choices=[('client', '딜러에게 보낸 메시지'), ('agent', '평카인에게 보낸 메시지'), ('deliverer', '탁송기사에게 보낸 메시지')], max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to=pcar.helpers.PreprocessUploadPath(requestings.models.requesting_chatting_message.message_image_path_getter, use_uuid_name=True), verbose_name='채팅 이미지')),
            ],
            options={
                'verbose_name': '의뢰 채팅 메시지',
                'verbose_name_plural': '의뢰 채팅 메시지 목록',
                'db_table': 'requesting_chatting_messages',
            },
        ),
        migrations.CreateModel(
            name='RequestingHistory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='접수 시각')),
                ('type', models.CharField(choices=[('EVALUATION_DELIVERY', '평카 탁송'), ('INSPECTION_DELIVERY', '검수 탁송'), ('ONLY_DELIVERY', '일반 탁송')], max_length=32, verbose_name='의뢰 형태')),
                ('status', models.CharField(choices=[('WAITING_AGENT', '평카인 배정 대기'), ('WAITING_WORKING', '업무 시작 대기'), ('EVALUATING', '평카/검수중'), ('EVALUATION_DONE', '평카/검수 완료'), ('WAITING_DELIVERER', '탁송 기사 배정 대기'), ('WAITING_DELIVERY_WORKING', '탁송 시작 대기'), ('DELIVERING', '탁송중'), ('DELIVERING_DONE', '탁송 완료'), ('CANCELLED', '서비스 취소'), ('DONE', '서비스 완료')], max_length=64, verbose_name='의뢰 상태')),
                ('is_delivery_transferred', models.BooleanField(default=False, verbose_name='탁송 양도 여부')),
                ('reservation_date', models.DateTimeField(blank=True, null=True, verbose_name='예약 날짜')),
                ('estimated_service_date', models.DateTimeField(blank=True, null=True, verbose_name='서비스 예정 시작 날짜')),
                ('distance_between_source_destination', models.FloatField(default=0, verbose_name='출발지와 목적지간 거리')),
                ('evaluation_cost', models.PositiveIntegerField(default=0, verbose_name='평카 요금')),
                ('inspection_cost', models.PositiveIntegerField(default=0, verbose_name='검수 요금')),
                ('delivering_cost', models.PositiveIntegerField(default=0, verbose_name='탁송 요금')),
                ('additional_suggested_cost', models.PositiveIntegerField(default=0, verbose_name='의뢰인 추가 제안 요금')),
                ('evaluation_finished_at', models.DateTimeField(blank=True, null=True, verbose_name='평카(검수) 일시')),
                ('confirmation_inspection_result_at', models.DateTimeField(blank=True, null=True, verbose_name='의뢰인 검수 결과 확인 일시')),
                ('is_onsite_payment', models.BooleanField(verbose_name='현장 결제 유무')),
                ('memo', models.TextField(blank=True, max_length=300, null=True, verbose_name='기타내용')),
            ],
            options={
                'verbose_name': '의뢰',
                'verbose_name_plural': '의뢰 목록',
                'db_table': 'requesting_histories',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성 시각')),
                ('content', models.TextField(max_length=500, verbose_name='리뷰 내용')),
                ('requesting_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='requestings.requestinghistory', verbose_name='대상 의뢰')),
            ],
            options={
                'verbose_name': '리뷰',
                'verbose_name_plural': '리뷰 목록',
                'db_table': 'reviews',
            },
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=pcar.helpers.PreprocessUploadPath(requestings.models.review.review_image_path_getter, use_uuid_name=True), verbose_name='리뷰 이미지')),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='requestings.review', verbose_name='대상 이미지')),
            ],
            options={
                'verbose_name': '리뷰 이미지',
                'verbose_name_plural': '리뷰 이미지 목록',
                'db_table': 'review_images',
            },
        ),
        migrations.CreateModel(
            name='RequestingSettlement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='정산 번호')),
                ('requesting_end_at', models.DateTimeField(auto_now_add=True, verbose_name='정산 시각')),
                ('evaluation_cost', models.PositiveIntegerField(default=0, verbose_name='평카 요금')),
                ('inspection_cost', models.PositiveIntegerField(default=0, verbose_name='검수 요금')),
                ('delivering_cost', models.PositiveIntegerField(default=0, verbose_name='탁송 요금')),
                ('additional_suggested_cost', models.PositiveIntegerField(default=0, verbose_name='의뢰인 추가 제안 요금')),
                ('total_additional_cost', models.PositiveIntegerField(default=0, verbose_name='총 추가 요금')),
                ('is_onsite_payment', models.BooleanField(verbose_name='현장 결제 유무')),
                ('requesting_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settlement', to='requestings.requestinghistory', verbose_name='대상 의뢰')),
            ],
            options={
                'verbose_name': '의뢰 정산',
                'verbose_name_plural': '의뢰 정산 목록',
                'db_table': 'requesting_settlements',
            },
        ),
    ]
