# Generated by Django 4.0.6 on 2022-11-23 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestings', '0003_alter_bulkrequesting_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_exposing_to_dealer',
            field=models.BooleanField(default=False, verbose_name='의뢰인용 앱 메인 노출 유무'),
        ),
    ]
