# Generated by Django 4.0.6 on 2022-11-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestings', '0005_review_name_alter_review_requesting_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='작성자 이름 (필수 아님, 의뢰로 등록된 경우 의뢰자 이름 우선)'),
        ),
    ]
