# Generated by Django 4.0.6 on 2023-02-01 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('requestings', '0006_alter_review_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryRegionDivision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='지역 이름')),
                ('parent_address_name', models.CharField(max_length=32, verbose_name='소속 시/군 이름')),
                ('dong_list', models.TextField(verbose_name='소속 동 리스트 (개행으로 구분)')),
            ],
            options={
                'verbose_name': '탁송 요금 산정용 지역 분할',
                'verbose_name_plural': '탁송 요금 산정용 지역 분할 목록',
                'db_table': 'delivery_region_divisions',
            },
        ),
        migrations.CreateModel(
            name='DeliveryFeeRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_fee', models.PositiveIntegerField(default=0, verbose_name='탁송 요금')),
                ('arrival_region_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_relation_as_arrival', to='requestings.deliveryregiondivision', verbose_name='도착지 지역')),
                ('departure_region_division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_relation_as_departure', to='requestings.deliveryregiondivision', verbose_name='출발지 지역')),
            ],
            options={
                'verbose_name': '탁송 요금 지역 관계',
                'verbose_name_plural': '탁송 요금 지역 관계 목록',
                'db_table': 'delivery_fee_relations',
            },
        ),
    ]
