# Generated by Django 4.0.6 on 2023-02-03 14:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requestings', '0008_remove_deliveryregiondivision_dong_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryregiondivision',
            name='gu_dong_list',
            field=models.TextField(verbose_name='소속 구, 법정동 리스트 (개행으로 구분)'),
        ),
        migrations.AlterField(
            model_name='requestinghistory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='의뢰 접수 일시'),
        ),
        migrations.AlterField(
            model_name='requestingsettlement',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='정산번호'),
        ),
        migrations.AlterField(
            model_name='requestingsettlement',
            name='total_additional_cost',
            field=models.PositiveIntegerField(default=0, verbose_name='기타 금액 합계'),
        ),
        migrations.CreateModel(
            name='RefererSettlement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='정산 번호')),
                ('requesting_end_at', models.DateTimeField(auto_now_add=True, verbose_name='정산 시각')),
                ('revenue', models.PositiveIntegerField(default=0, verbose_name='홍보비 수익 금액')),
                ('requesting_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referer_settlement', to='requestings.requestinghistory', verbose_name='대상 의뢰')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referer_settlements', to=settings.AUTH_USER_MODEL, verbose_name='정산 대상 평카인')),
            ],
            options={
                'verbose_name': '홍보비 정산',
                'verbose_name_plural': '홍보비 정산 목록',
                'db_table': 'referer_settlements',
            },
        ),
    ]
