# Generated by Django 4.0.6 on 2023-02-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestings', '0011_requestingadditionalcost_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requestingsettlement',
            name='total_additional_cost',
        ),
        migrations.AddField(
            model_name='requestingsettlement',
            name='additional_costs',
            field=models.ManyToManyField(related_name='contained_settlements', to='requestings.requestingadditionalcost', verbose_name='해당 추가 요금'),
        ),
    ]
