# Generated by Django 4.0.6 on 2023-02-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestings', '0012_remove_requestingsettlement_total_additional_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestingadditionalcost',
            name='type',
            field=models.CharField(choices=[('주유비', '주유비'), ('대기비', '대기비'), ('기타', '기타')], default='기타', max_length=32, verbose_name='요금 구분'),
        ),
    ]
