# Generated by Django 4.0.6 on 2023-03-29 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestings', '0015_remove_deliveryregiondivision_exclude_gu_dong_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryregiondivision',
            name='gu_dong_list',
        ),
        migrations.RemoveField(
            model_name='deliveryregiondivision',
            name='parent_address_name',
        ),
        migrations.AddField(
            model_name='deliveryregiondivision',
            name='address_name',
            field=models.TextField(default='', verbose_name='소속 주소 (개행으로 구분)'),
            preserve_default=False,
        ),
    ]
