# Generated by Django 4.0.6 on 2023-05-16 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestings', '0016_remove_deliveryregiondivision_gu_dong_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referersettlement',
            name='tax',
            field=models.PositiveIntegerField(default=0, verbose_name='홍보비 수수료'),
        ),
        migrations.AddField(
            model_name='requestingsettlement',
            name='employment_insurance_price',
            field=models.IntegerField(default=0, verbose_name='수행자 고용보험 금액'),
        ),
        migrations.AddField(
            model_name='requestingsettlement',
            name='withholding_tax_price',
            field=models.IntegerField(default=0, verbose_name='수행자 원천징수 금액'),
        ),
    ]
