# Generated by Django 4.0.6 on 2024-03-06 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestings', '0017_referersettlement_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinghistory',
            name='delivery_proceed_decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='의뢰자 탁송 결정 시각'),
        ),
    ]
