# Generated by Django 4.0.6 on 2024-10-06 10:30

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('requestings', '0018_requestinghistory_delivery_proceed_decided_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinghistory',
            name='external_client_mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='원 의뢰자 핸드폰번호 (위탁 의뢰건만)'),
        ),
        migrations.AddField(
            model_name='requestinghistory',
            name='external_client_name',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='원 의뢰자 이름 (위탁 의뢰건만)'),
        ),
        migrations.AddField(
            model_name='requestinghistory',
            name='hook_url',
            field=models.URLField(blank=True, null=True, verbose_name='웹훅 URL'),
        ),
    ]
