# Generated by Django 4.0.6 on 2024-10-15 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestings', '0019_requestinghistory_external_client_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaangnRequestingHistory',
            fields=[
            ],
            options={
                'verbose_name': '당근마켓 의뢰',
                'verbose_name_plural': '당근마켓 의뢰목록',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requestings.requestinghistory',),
        ),
    ]
