# Generated by Django 4.0.6 on 2024-10-15 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestings', '0020_daangnrequestinghistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestinghistory',
            name='has_agent_delivery_start',
            field=models.BooleanField(default=False, verbose_name='의뢰인의 탁송 출발 여부'),
        ),
    ]
