# Generated by Django 4.0.6 on 2024-10-28 10:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_dealerprofile_is_alimtalk_receiving_and_more'),
        ('requestings', '0021_requestinghistory_has_agent_delivery_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='carbasicimage',
            name='sub_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='사진 보조 구분'),
        ),
        migrations.AddField(
            model_name='carbasicimage',
            name='type',
            field=models.CharField(choices=[('CAR_KEY', '차키'), ('DASHBOARD', '계기판'), ('EXTERIOR', '외장'), ('INTERIOR', '내장'), ('WHEEL', '휠'), ('REQUIRED_DOCUMENTS', '명의이전 구비서류')], default='EXTERIOR', max_length=32, verbose_name='사진 구분'),
        ),
        migrations.AlterField(
            model_name='requestinghistory',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='탁송만 하는 의뢰일 경우 공란으로 두세요', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='allocation_requestings', to='users.agent', verbose_name='담당 평가사 (탁송건일 경우 공란)'),
        ),
    ]
