# Generated by Django 4.0.6 on 2024-10-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_dealerprofile_is_alimtalk_receiving_and_more'),
        ('requestings', '0023_alter_carbasicimage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinghistory',
            name='fee_payment_histories',
            field=models.ManyToManyField(blank=True, null=True, related_name='fee_payment_histories', to='users.balancehistory', verbose_name='에이전트 수수료 결제 기록'),
        ),
        migrations.AlterField(
            model_name='requestinghistory',
            name='memo',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='메모 (특이사항)'),
        ),
    ]
