# Generated by Django 4.0.6 on 2024-11-01 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestings', '0025_alter_carbasicimage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carbasicimage',
            name='sub_type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='사진 보조 구분'),
        ),
    ]
