# Generated by Django 4.0.6 on 2024-12-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestings', '0027_alter_carbasicimage_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestinghistory',
            name='delivering_cost',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='탁송 요금'),
        ),
    ]
