# Generated by Django 4.0.6 on 2024-12-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestings', '0028_alter_requestinghistory_delivering_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryregiondivision',
            name='name',
            field=models.CharField(max_length=64, verbose_name='지역 이름'),
        ),
    ]
