# Generated by Django 4.0.6 on 2024-12-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestings', '0030_finisheddaangnrequestinghistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaangnRequestingSettlement',
            fields=[
            ],
            options={
                'verbose_name': '당근 의뢰 정산',
                'verbose_name_plural': '당근 의뢰 정산목록',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('requestings.requestingsettlement',),
        ),
        migrations.AddField(
            model_name='requestinghistory',
            name='skip_fee_for_deliverer',
            field=models.BooleanField(default=False, verbose_name='탁송기사 수수료 면제 여부'),
        ),
    ]
