# Generated by Django 4.0.6 on 2022-09-19 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_test_account',
            field=models.BooleanField(default=False, verbose_name='테스트용 계정 (애플 심사 등)'),
        ),
    ]
