# Generated by Django 4.0.6 on 2023-01-30 15:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_agentlocation_is_end_of_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='business_categories',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('중고차 매매업', '중고차 매매업'), ('신차매매업', '신차매매업'), ('중고차딜러', '중고차딜러'), ('신차딜러', '신차딜러'), ('렌트카', '렌트카'), ('선물사 (리스, 채권)', '선물사 (리스, 채권)'), ('기타', '기타')], max_length=32, null=True, verbose_name='사업분류'),
        ),
    ]
