# Generated by Django 4.0.6 on 2023-01-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_agentprofile_activity_area'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentprofile',
            old_name='activity_area',
            new_name='activity_areas',
        ),
    ]
