# Generated by Django 4.0.6 on 2023-02-22 12:05

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields
import pcar.helpers
import users.models.dealer_company


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_balancehistory_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerCompany',
            fields=[
                ('id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True, verbose_name='업체 코드')),
                ('company_name', models.CharField(max_length=100, verbose_name='상호명')),
                ('business_registration_number', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='사업자 등록번호')),
                ('representative_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='대표자 이름')),
                ('business_registration', models.ImageField(blank=True, null=True, upload_to=pcar.helpers.PreprocessUploadPath(users.models.dealer_company.business_registration_image_path_getter, 'business_registration', use_uuid_name=True), verbose_name='사업자등록증 사본')),
                ('business_items', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('평가', '평가'), ('검수', '검수'), ('탁송', '탁송'), ('중개', '중개')], max_length=32, null=True, verbose_name='회사 아이템')),
                ('business_categories', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('중고차 매매업', '중고차 매매업'), ('신차매매업', '신차매매업'), ('중고차딜러', '중고차딜러'), ('신차딜러', '신차딜러'), ('렌트카', '렌트카'), ('선물사 (리스, 채권)', '선물사 (리스, 채권)'), ('수출', '수출'), ('기타', '기타')], max_length=32, null=True, verbose_name='사업분류')),
            ],
            options={
                'verbose_name': '딜러 업체',
                'verbose_name_plural': '딜러 업체 목록',
                'db_table': 'dealer_company',
            },
        ),
        migrations.RemoveField(
            model_name='dealerprofile',
            name='business_categories',
        ),
        migrations.RemoveField(
            model_name='dealerprofile',
            name='business_category',
        ),
        migrations.RemoveField(
            model_name='dealerprofile',
            name='business_items',
        ),
        migrations.RemoveField(
            model_name='dealerprofile',
            name='business_registration',
        ),
        migrations.RemoveField(
            model_name='dealerprofile',
            name='business_registration_number',
        ),
        migrations.RemoveField(
            model_name='dealerprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='dealerprofile',
            name='representative_name',
        ),
        migrations.AddField(
            model_name='dealerprofile',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers', to='users.dealercompany', verbose_name='소속 업체'),
        ),
    ]
