# Generated by Django 4.0.6 on 2023-02-22 12:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_dealercompany_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealercompany',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, verbose_name='고유 코드 (파일 업로드용)'),
        ),
    ]
