# Generated by Django 4.0.6 on 2023-02-22 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_rename_company_name_dealercompany_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealerprofile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dealers', to='users.dealercompany', verbose_name='소속 업체'),
        ),
    ]
