# Generated by Django 4.0.6 on 2023-03-11 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_dealerprofile_require_publish_bill_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='ability_to_acquire_education',
            field=models.CharField(blank=True, choices=[('상', '상'), ('중', '중'), ('하', '하')], max_length=32, null=True, verbose_name='교육습득능력'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='appointment_time_score',
            field=models.CharField(blank=True, choices=[('상', '상'), ('중', '중'), ('하', '하')], max_length=32, null=True, verbose_name='평카인 레벨 시간 준수'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='closed_days',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='휴무요일'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='collective_education_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='집체교육 (회)'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='completion_test_result',
            field=models.CharField(blank=True, choices=[('초급', '초급'), ('중급', '중급'), ('고급', '고급')], max_length=32, null=True, verbose_name='수료 테스트 결과'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='cs_score',
            field=models.CharField(blank=True, choices=[('상', '상'), ('중', '중'), ('하', '하')], max_length=32, null=True, verbose_name='CS 레벨'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='current_working_area',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='현근무지'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='delivery_score',
            field=models.CharField(blank=True, choices=[('상', '상'), ('중', '중'), ('하', '하')], max_length=32, null=True, verbose_name='탁송 레벨'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='education_grade',
            field=models.CharField(blank=True, choices=[('A', 'A레벨'), ('B', 'B레벨'), ('C', 'C레벨')], max_length=64, null=True, verbose_name='교육등급'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='education_participation',
            field=models.BooleanField(blank=True, null=True, verbose_name='교육참여도'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='evaluation_score',
            field=models.CharField(blank=True, choices=[('상', '상'), ('중', '중'), ('하', '하')], max_length=32, null=True, verbose_name='평가 레벨'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='first_working_area',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='최초 근무지역'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='inspection_score',
            field=models.CharField(blank=True, choices=[('상', '상'), ('중', '중'), ('하', '하')], max_length=32, null=True, verbose_name='검수 레벨'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='intimacy',
            field=models.BooleanField(blank=True, null=True, verbose_name='이웃과의 친밀 여부'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='supplementary_education_count',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='보수교육 (회)'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='tendency',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='성향'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='total_delivery_count',
            field=models.PositiveIntegerField(default=0, max_length='총 탁송 횟수'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='total_evaluation_count',
            field=models.PositiveIntegerField(default=0, max_length='총 평가 횟수'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='total_inspection_count',
            field=models.PositiveIntegerField(default=0, max_length='총 검수 횟수'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='total_marketing_count',
            field=models.PositiveIntegerField(default=0, max_length='총 홍보 횟수'),
        ),
        migrations.AddField(
            model_name='agentprofile',
            name='weekend_charge_working_area',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='현 주말 전담반 근무지역'),
        ),
    ]
