# Generated by Django 4.0.6 on 2023-03-12 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_agentprofile_monthly_insurance_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealercompany',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='이메일 주소'),
        ),
    ]
