# Generated by Django 4.0.6 on 2023-03-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_dealercompany_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealercompany',
            name='company_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='대표번호'),
        ),
        migrations.AddField(
            model_name='dealercompany',
            name='person_in_charge',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='담당자 명'),
        ),
        migrations.AddField(
            model_name='dealercompany',
            name='person_in_charge_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='담당자 연락처'),
        ),
        migrations.AddField(
            model_name='dealercompany',
            name='person_in_charge_position',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='담당자 직위'),
        ),
        migrations.AddField(
            model_name='dealercompany',
            name='representative_number',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='대표자 연락처'),
        ),
    ]
