# Generated by Django 4.0.6 on 2023-03-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_dealercompany_company_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealercompany',
            name='type',
            field=models.CharField(blank=True, choices=[('딜러', '딜러'), ('상사', '상사'), ('공업사', '공업사'), ('캠핑카', '캠핑카'), ('튜닝', '튜닝'), ('용품', '용품'), ('정비', '정비'), ('렌트', '렌트'), ('법인', '법인'), ('리스', '리스')], max_length=64, null=True, verbose_name='고객(협력사) 분류'),
        ),
    ]
