# Generated by Django 4.0.6 on 2023-03-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_dealercompany_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealercompany',
            name='business_opening_at',
            field=models.DateField(blank=True, null=True, verbose_name='거래개설일자'),
        ),
    ]
