# Generated by Django 4.0.6 on 2023-03-15 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_dealercompany_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='birthday',
            field=models.DateField(blank=True, null=True, verbose_name='생년월일'),
        ),
    ]
