# Generated by Django 4.0.6 on 2023-03-15 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_agentprofile_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='home_address',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='주소'),
        ),
    ]
