# Generated by Django 4.0.6 on 2023-03-15 09:32

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_agentprofile_home_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='affiliated_area',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='소속지역'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='activity_areas',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('평카', '평카'), ('평카탁송', '평카탁송'), ('검수탁송', '검수탁송'), ('일반탁송', '일반탁송'), ('홍보 (영업)', '홍보 (영업)'), ('기타', '기타')], max_length=32, null=True, verbose_name='활동 현황'),
        ),
    ]
