# Generated by Django 4.0.6 on 2023-03-15 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_agentprofile_first_working_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentprofile',
            name='dotori_status',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='도토리 현황'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='appointment_time_score',
            field=models.CharField(blank=True, choices=[('상', '상'), ('중', '중'), ('하', '하')], max_length=32, null=True, verbose_name='시간 준수수준'),
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='intimacy',
            field=models.BooleanField(blank=True, null=True, verbose_name='이웃친밀도'),
        ),
    ]
