# Generated by Django 4.0.6 on 2023-03-20 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_agentprofile_referer_reward_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentprofile',
            old_name='referer_reward_rate',
            new_name='referer_revenue_rate',
        ),
    ]
