# Generated by Django 4.0.6 on 2024-03-06 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0035_withdrawalrequesting_withdrawal_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(verbose_name='가입 일자'),
        ),
        migrations.AlterField(
            model_name='user',
            name='referer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brought_users', to='users.agent', verbose_name='추천인'),
        ),
    ]
