# Generated by Django 4.0.6 on 2024-03-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_alter_user_created_at_alter_user_referer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, help_text='보험 만료 시 해당 평카인은 오더에 배차가 불가능합니다', null=True, verbose_name='보험 만료 일시'),
        ),
    ]
