# Generated by Django 4.0.6 on 2024-10-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_user_api_id_user_api_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_usage_type',
            field=models.CharField(blank=True, choices=[('당근마켓', 'DAANGN'), ('기타', 'OTHERS')], max_length=16, null=True, verbose_name='API 사용 구분'),
        ),
    ]
