# Generated by Django 4.0.6 on 2024-10-06 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_user_api_usage_type_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_usage_type',
            field=models.CharField(blank=True, choices=[('DAANGN', '당근마켓'), ('OTHERS', '기타')], max_length=16, null=True, verbose_name='API 사용 구분'),
        ),
    ]
