# Generated by Django 4.0.6 on 2024-10-10 17:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_alter_user_api_usage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealerprofile',
            name='is_alimtalk_receiving',
            field=models.BooleanField(default=True, verbose_name='카카오 알림톡 수신 여부'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='01000000000', max_length=128, region=None, verbose_name='핸드폰 번호'),
            preserve_default=False,
        ),
    ]
