# Generated by Django 4.0.6 on 2024-11-04 13:03

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0041_dealerprofile_is_alimtalk_receiving_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='핸드폰 번호'),
        ),
    ]
