# Generated by Django 4.0.6 on 2024-12-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0042_alter_user_mobile_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentprofile',
            name='id',
            field=models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='평카인 사번'),
        ),
    ]
