# Generated by Django 4.0.6 on 2024-12-04 12:40

from django.db import migrations, models
import pcar.helpers
import users.models.agent_profile


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_alter_agentprofile_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentprofile',
            options={'verbose_name': '에이전트 프로필', 'verbose_name_plural': '에이전트 프로필 목록'},
        ),
        migrations.AlterField(
            model_name='agentprofile',
            name='profile_image',
            field=models.ImageField(blank=True, default='/default-user-image.jpg', null=True, upload_to=pcar.helpers.PreprocessUploadPath(users.models.agent_profile.profile_image_image_path_getter, filename_prefix='agent_profile_image', use_uuid_name=True), verbose_name='평카인 프로필 사진'),
        ),
    ]
