# Generated by Django 4.0.6 on 2024-12-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0044_alter_agentprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='balancehistory',
            name='sub_type',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='금액 세부 구분'),
        ),
    ]
