# Generated by Django 4.0.6 on 2024-12-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_balancehistory_sub_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balancehistory',
            name='sub_type',
            field=models.CharField(blank=True, choices=[('agent', '에이전트 수수료 구분용 (평카/검수)'), ('deliverer', '탁송기사 수수료 구분용')], max_length=32, null=True, verbose_name='금액 세부 구분'),
        ),
    ]
