# Generated by Django 4.0.6 on 2022-09-15 15:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coord', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326, verbose_name='주소 좌표')),
                ('road_address', models.CharField(max_length=300, verbose_name='도로명 주소')),
                ('detail_address', models.CharField(blank=True, max_length=300, null=True, verbose_name='상세 주소')),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='경유지 연락처')),
            ],
            options={
                'verbose_name': '주소 정보',
                'verbose_name_plural': '주소 정보 목록',
                'db_table': 'locations',
            },
        ),
    ]
