# Generated by Django 4.0.6 on 2023-02-19 12:11

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonlocation',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='연락처 (해당 주소지가 경유지일 경우만)'),
        ),
        migrations.AlterField(
            model_name='commonlocation',
            name='detail_address',
            field=models.CharField(default='', max_length=300, verbose_name='상세 주소'),
        ),
    ]
