# Generated by Django 4.0.6 on 2023-04-13 14:48

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_alter_commonlocation_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonlocation',
            name='contact',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='연락처'),
        ),
    ]
