# Generated by Django 4.0.6 on 2022-11-23 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carhistoryresult',
            name='is_scrapping',
            field=models.BooleanField(default=True, verbose_name='현재 크롤링 진행중 여부'),
        ),
    ]
