# Generated by Django 4.0.6 on 2022-11-26 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_carhistoryresult_is_scrapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carevaluationresult',
            name='have_airbag_warning_light',
        ),
        migrations.RemoveField(
            model_name='carevaluationresult',
            name='have_engine_check_light',
        ),
        migrations.RemoveField(
            model_name='carevaluationresult',
            name='side_mirror_cover_marker',
        ),
        migrations.RemoveField(
            model_name='carevaluationresult',
            name='side_mirror_mirror_marker',
        ),
        migrations.RemoveField(
            model_name='carevaluationresult',
            name='side_mirror_repeater_marker',
        ),
        migrations.AddField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('오토', '오토'), ('스틱', '스틱')], max_length=10, null=True, verbose_name='변속기 분류'),
        ),
        migrations.AddField(
            model_name='carevaluationresult',
            name='abnormal_while_driving',
            field=models.TextField(blank=True, null=True, verbose_name='주행중 이상 증상 관련 메모'),
        ),
        migrations.AddField(
            model_name='carevaluationresult',
            name='drivers_side_mirror_cover_marker',
            field=models.JSONField(blank=True, null=True, verbose_name='운전석 사이드 미러 덮개 데미지'),
        ),
        migrations.AddField(
            model_name='carevaluationresult',
            name='drivers_side_mirror_mirror_marker',
            field=models.JSONField(blank=True, null=True, verbose_name='운전석 사이드 미러 거울 데미지'),
        ),
        migrations.AddField(
            model_name='carevaluationresult',
            name='drivers_side_mirror_repeater_marker',
            field=models.JSONField(blank=True, null=True, verbose_name='운전석 사이드 미러 리피터 데미지'),
        ),
        migrations.AddField(
            model_name='carevaluationresult',
            name='instrument_panel_warning_memo',
            field=models.TextField(blank=True, null=True, verbose_name='계기판 경고등 관련 메모'),
        ),
        migrations.AddField(
            model_name='carevaluationresult',
            name='leakage_memo',
            field=models.TextField(blank=True, null=True, verbose_name='누유 관련 메모'),
        ),
        migrations.AddField(
            model_name='carevaluationresult',
            name='option_malfunction_memo',
            field=models.TextField(blank=True, null=True, verbose_name='옵션 기능 작동 이상 관련 메모'),
        ),
        migrations.AddField(
            model_name='carevaluationresult',
            name='passenger_side_mirror_cover_marker',
            field=models.JSONField(blank=True, null=True, verbose_name='조수석 사이드 미러 덮개 데미지'),
        ),
        migrations.AddField(
            model_name='carevaluationresult',
            name='passenger_side_mirror_mirror_marker',
            field=models.JSONField(blank=True, null=True, verbose_name='조수석 사이드 미러 거울 데미지'),
        ),
        migrations.AddField(
            model_name='carevaluationresult',
            name='passenger_side_mirror_repeater_marker',
            field=models.JSONField(blank=True, null=True, verbose_name='조수석 사이드 미러 리피터 데미지'),
        ),
        migrations.AddField(
            model_name='carevaluationresult',
            name='smart_key_counts',
            field=models.IntegerField(default=0, verbose_name='스마트 차키 갯수'),
        ),
        migrations.AlterField(
            model_name='car',
            name='classification',
            field=models.CharField(blank=True, choices=[('대형', '대형'), ('화물', '화물'), ('렉카', '렉카'), ('추레라', '추레라'), ('캠핑카', '캠핑카')], max_length=10, null=True, verbose_name='차량 분류'),
        ),
    ]
