# Generated by Django 4.0.6 on 2022-11-26 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_remove_carevaluationresult_have_airbag_warning_light_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carevaluationresult',
            old_name='abnormal_while_driving',
            new_name='abnormal_while_driving_memo',
        ),
    ]
