# Generated by Django 4.0.6 on 2024-10-06 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_alter_car_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='external_car_image_url',
            field=models.URLField(blank=True, null=True, verbose_name='차량 이미지 (외부 업로드)'),
        ),
    ]
