# Generated by Django 4.0.6 on 2022-11-23 09:27

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('termsofuse', '서비스이용약관'), ('privacy', '개인정보처리방침')], max_length=32, unique=True, verbose_name='약관 종류')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='내용')),
            ],
            options={
                'verbose_name': '약관',
                'verbose_name_plural': '약관 목록',
                'db_table': 'agreements',
            },
        ),
    ]
