#!/bin/bash

source $(dirname $0)/utils

check_base_directory

docker build -t bridcar-dev -f configs/docker/dev/Dockerfile . --no-cache

docker-compose -f configs/docker/dev/docker-compose.yml down
docker-compose -f configs/docker/dev/docker-compose.yml up
