#!/bin/bash

source $(dirname $0)/utils

check_base_directory

docker-compose -f configs/docker/dev/docker-compose.yml exec $(grep -oP '\K(([a-z]|_)+)(?=\.settings)' src/manage.py)-api-server /bin/bash
