# Generated by Django 4.0.6 on 2024-10-06 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requestings', '0019_requestinghistory_external_client_mobile_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaangnRequestingInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='입금 여부 (확정 여부)')),
                ('requesting_history', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daangn_requesting_information', to='requestings.requestinghistory', verbose_name='대상 의뢰')),
            ],
            options={
                'verbose_name': '당근 의뢰 추가 정보',
                'verbose_name_plural': '당근 의뢰 추가 정보 목록',
                'db_table': 'daangn_requesting_informations',
            },
        ),
    ]
