# Generated by Django 4.0.6 on 2024-10-11 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daangn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daangnrequestinginformation',
            name='initial_reservation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='최초 예약 시간'),
        ),
    ]
