# Generated by Django 4.0.6 on 2024-10-28 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daangn', '0002_daangnrequestinginformation_initial_reservation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='DaangnRequestingRequiredDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, verbose_name='서류 구분 값')),
                ('title', models.CharField(max_length=128, verbose_name='서류 제목')),
                ('description', models.CharField(max_length=128, verbose_name='서류에 대한 설명')),
                ('daangn_requesting_information', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='daangn.daangnrequestinginformation', verbose_name='해당 당근 의뢰 정보')),
            ],
            options={
                'verbose_name': '당근 의뢰 필요 서류',
                'verbose_name_plural': '당근 의뢰 필요 서류 목록',
                'db_table': 'daangn_requesting_required_documents',
            },
        ),
    ]
