# Generated by Django 4.0.6 on 2024-10-28 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daangn', '0004_daangnrequestingrequireddocument_is_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daangnrequestingrequireddocument',
            name='daangn_requesting_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='required_documents', to='daangn.daangnrequestinginformation', verbose_name='해당 당근 의뢰 정보'),
        ),
    ]
