# Generated by Django 4.0.6 on 2024-10-31 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daangn', '0005_alter_daangnrequestingrequireddocument_daangn_requesting_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daangnrequestingrequireddocument',
            name='key',
            field=models.CharField(max_length=128, verbose_name='서류 구분 값'),
        ),
    ]
