# Generated by Django 4.0.6 on 2024-11-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daangn', '0007_alter_daangnrequestingrequireddocument_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='daangnrequestinginformation',
            name='is_forced_exposure',
            field=models.BooleanField(default=False, verbose_name='확정 무관 강제 노출 여부'),
        ),
    ]
